USE coop_items_db;

DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS scoreLists;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS teams;

CREATE TABLE IF NOT EXISTS teams
(
	id VARCHAR(4) NOT NULL UNIQUE,
    name VARCHAR(15) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users
(
	name VARCHAR(20) NOT NULL,
    teamId VARCHAR(4) NOT NULL,
    PRIMARY KEY(name, teamId),
    FOREIGN KEY(teamId) REFERENCES teams(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS scoreLists
(
	id MEDIUMINT UNSIGNED AUTO_INCREMENT,
    teamId VARCHAR(4) NOT NULL,
    totalScore SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(teamId) REFERENCES teams(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS scores
(
	scoreListId MEDIUMINT UNSIGNED NOT NULL,
    teamId VARCHAR(4) NOT NULL,
    userName VARCHAR(20) NOT NULL,
    score TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY(scoreListId) REFERENCES scoreLists(id),
    FOREIGN KEY(teamId) REFERENCES teams(id),
    FOREIGN KEY(userName) REFERENCES users(name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS items
(
	name VARCHAR(45) NOT NULL,
    teamId VARCHAR(4) NOT NULL,
    scoreListId MEDIUMINT UNSIGNED,
    PRIMARY KEY(name, teamId),
    FOREIGN KEY(teamId) REFERENCES teams(id),
    FOREIGN KEY(scoreListId) REFERENCES scoreLists(id)
) ENGINE=InnoDB;
